### PR TITLE
Test across multiple environments

### PR DESCRIPTION
**Pull request by paulfalgout**
Also update underscore dependency
And remove lodash dev dependency so matrix works

### CODE REVIEW

**Comment by paulfalgout** [comment]
Resolved #115 
Resolves #111 
Resolves #87
@brentli1 ping for :eyes: and :+1: :arrow_right: :shipit:

**Comment by paulfalgout** [comment]
Geez.. is code climate not working..

**Comment by paulfalgout** [comment]
code climate wasn't getting the code from travis.. was not a code thing... this should be good to go

**Comment by brentli1** [comment]
:+1:

**Pull request merged**
